SCMOD-9181 :Update Dockerfile opensuse jre11 image
CAFapi/opensuse-tomcat-jre11-image pull request #14
Opened 2020-09-14 16:21 UTC by gaana-vishwnath

2020-09-14 16:22 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](http://sou-jenkins2.swinfra.net:8080/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=CAFapi&REPO_NAME=opensuse-tomcat-jre11-image&BRANCH_NAME=SCMOD-9181) to go ahead and create the build...

2020-09-14 16:23 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/CAFapi/job/CAFapi~opensuse-tomcat-jre11-image~SCMOD-9181~CI

2020-09-14 16:30 UTC, michael-bryson requested changes

2020-09-14 16:30 UTC, michael-bryson commented on opensuse-tomcat-jre11-image/src/main/docker/Dockerfile
> +FROM cafinternal/prereleases:opensuse-jdk11-3.1.0-SNAPSHOT
Why are you changing from jre to jdk?

2020-09-15 09:15 UTC, gaana-vishwnath commented on opensuse-tomcat-jre11-image/src/main/docker/Dockerfile
> +FROM cafinternal/prereleases:opensuse-jdk11-3.1.0-SNAPSHOT
corrected

2020-09-15 09:24 UTC, gaana-vishwnath commented
Can you kindly review

2020-09-15 09:44 UTC, michael-bryson approved these changes

2020-09-15 09:45 UTC, merged