SCMOD-11683: Change Digester log level to info
CAFapi/opensuse-tomcat-jre11-image pull request #16
Opened 2020-11-16 20:26 UTC by xbreizh

2020-11-16 20:29 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](http://sou-jenkins2.swinfra.net:8080/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=CAFapi&REPO_NAME=opensuse-tomcat-jre11-image&BRANCH_NAME=SCMOD-11683) to go ahead and create the build...

2020-11-16 20:33 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/CAFapi/job/CAFapi~opensuse-tomcat-jre11-image~SCMOD-11683~CI

2020-11-17 18:15 UTC, dermot-hardy requested changes
I don't understand how this could possibly change anything.  (In fairness I don't understand the `org.apache.catalina` one already listed there either.)  Regardless I need that demo'ed to me.

2020-11-17 18:40 UTC, xbreizh commented
I have been running tests with the audit-service project with:
 
1. develop (using tomcat image without those changes)
   -> build has been killed after 1h20. It generated 2,6go logs
2.  SCMOD-9609 (using tomcat after those changes)
   -> build completed in 20mn

1- I couldn't find any evidence of looping happening. There was a lot of Digester logs being generated at debug level.
From the 2.6go logs, 2.3go are with "digester"

![image](https://user-images.githubusercontent.com/1658429/99432611-4c33c000-2904-11eb-96b9-a86cd47c0ec5.png)

2020-11-17 20:42 UTC, closed without merging